### PR TITLE
adding missing version field from package.json

### PR DESCRIPTION
**Pull request by toddradigan**
*note this was causing problems using https://github.com/Brightspace/license-checker-ci

### CODE REVIEW

**Comment by dlockhart** [comment]
Are you using NPM instead of Bower to install? In most of our components, NPM is currently only used a development/CI build/test tool and Bower is used for package/dependency management. That's going to change in the coming months though since Bower is EOLing.

**Comment by toddradigan** [comment]
Currently using bower to install.  The project (https://github.com/Brightspace/manager-view-fra) is using license-checker-ci (https://github.com/Brightspace/license-checker-ci) to validate package licenses.  The problem I'm currently running into is that it gets unhappy if there is no version, but I can add that to bower.json (instead of, or in addition to, package.json)

**Comment by dlockhart** [comment]
Hmm, interesting. The thing is... with the Bower stuff you don't actually put a version in the `bower.json` file -- in fact, [it's deprecated](https://github.com/bower/spec/blob/master/json.md#version) from the spec. Instead, we just create tagged releases for the versions and Bower figures everything out based on semver.

So ideally `license-checker` could be changed such that for Bower dependencies it does a semver resolution instead?

**Comment by toddradigan** [comment]
Oooh, that is interesting.  I'll investigate changes to `license-checker`.  I won't close this just yet, but for now consider it at least "on hold"

**Comment by dlockhart** [comment]
Cool sounds good -- let me know if you need any help.

**Pull request closed without merging**
